---
openapi: 3.0.1
info:
  title: PNW Mutual Aid API V1
  description: 'An Independent Project for Ruby on Rails - Building an API for Team Week'
  version: v1
  license:
    name: MIT
paths:
  "/resources":
    get:
      summary: list mutual aid resources
      responses:
        '200':
          description: successful
    post:
      summary: creates a resource
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                website:
                  type: string
                category:
                  type: string
                address:
                  type: string
              required:
              - name
              - website
              - category
              - address
  "/resources/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: shows a resource with a specific id
      responses:
        '200':
          description: successful
    patch:
      summary: updates a resource with a specific id
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                website:
                  type: string
                category:
                  type: string
                address:
                  type: string
    put:
      summary: updates a resource with a specific id
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                website:
                  type: string
                category:
                  type: string
                address:
                  type: string
    delete:
      summary: deletes a resource with a specific id
      responses:
        '200':
          description: successful
  "/resources/":
    parameters:
    - name: name
      in: query
      description: name
      schema:
        type: string
    get:
      summary: returns a resource by `name` or `name ilike?`
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
